/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsageRouteImport } from './routes/usage'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as MySettingsRouteImport } from './routes/my-settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as CloudAgentsRouteImport } from './routes/cloud-agents'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentsIndexRouteImport } from './routes/agents/index'
import { Route as ReviewStylesRouteImport } from './routes/review_.styles'
import { Route as AgentsInstructionsRouteImport } from './routes/agents_.instructions'
import { Route as AgentsThreadIdRouteImport } from './routes/agents/$threadId'
import { Route as AgentsAutomationsIndexRouteImport } from './routes/agents/automations/index'
import { Route as ReviewRepositoriesOwnerRouteImport } from './routes/review_.repositories.$owner'
import { Route as AgentsAutomationsNewRouteImport } from './routes/agents/automations/new'
import { Route as AgentsAutomationsScheduleIdRouteImport } from './routes/agents/automations/$scheduleId'

const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const MySettingsRoute = MySettingsRouteImport.update({
  id: '/my-settings',
  path: '/my-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const CloudAgentsRoute = CloudAgentsRouteImport.update({
  id: '/cloud-agents',
  path: '/cloud-agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgentsRoute,
} as any)
const ReviewStylesRoute = ReviewStylesRouteImport.update({
  id: '/review_/styles',
  path: '/review/styles',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsInstructionsRoute = AgentsInstructionsRouteImport.update({
  id: '/agents_/instructions',
  path: '/agents/instructions',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsThreadIdRoute = AgentsThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => AgentsRoute,
} as any)
const AgentsAutomationsIndexRoute = AgentsAutomationsIndexRouteImport.update({
  id: '/automations/',
  path: '/automations/',
  getParentRoute: () => AgentsRoute,
} as any)
const ReviewRepositoriesOwnerRoute = ReviewRepositoriesOwnerRouteImport.update({
  id: '/review_/repositories/$owner',
  path: '/review/repositories/$owner',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsAutomationsNewRoute = AgentsAutomationsNewRouteImport.update({
  id: '/automations/new',
  path: '/automations/new',
  getParentRoute: () => AgentsRoute,
} as any)
const AgentsAutomationsScheduleIdRoute =
  AgentsAutomationsScheduleIdRouteImport.update({
    id: '/automations/$scheduleId',
    path: '/automations/$scheduleId',
    getParentRoute: () => AgentsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agents': typeof AgentsRouteWithChildren
  '/cloud-agents': typeof CloudAgentsRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/my-settings': typeof MySettingsRoute
  '/review': typeof ReviewRoute
  '/usage': typeof UsageRoute
  '/agents/$threadId': typeof AgentsThreadIdRoute
  '/agents/instructions': typeof AgentsInstructionsRoute
  '/review/styles': typeof ReviewStylesRoute
  '/agents/': typeof AgentsIndexRoute
  '/agents/automations/$scheduleId': typeof AgentsAutomationsScheduleIdRoute
  '/agents/automations/new': typeof AgentsAutomationsNewRoute
  '/review/repositories/$owner': typeof ReviewRepositoriesOwnerRoute
  '/agents/automations/': typeof AgentsAutomationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cloud-agents': typeof CloudAgentsRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/my-settings': typeof MySettingsRoute
  '/review': typeof ReviewRoute
  '/usage': typeof UsageRoute
  '/agents/$threadId': typeof AgentsThreadIdRoute
  '/agents/instructions': typeof AgentsInstructionsRoute
  '/review/styles': typeof ReviewStylesRoute
  '/agents': typeof AgentsIndexRoute
  '/agents/automations/$scheduleId': typeof AgentsAutomationsScheduleIdRoute
  '/agents/automations/new': typeof AgentsAutomationsNewRoute
  '/review/repositories/$owner': typeof ReviewRepositoriesOwnerRoute
  '/agents/automations': typeof AgentsAutomationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agents': typeof AgentsRouteWithChildren
  '/cloud-agents': typeof CloudAgentsRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/my-settings': typeof MySettingsRoute
  '/review': typeof ReviewRoute
  '/usage': typeof UsageRoute
  '/agents/$threadId': typeof AgentsThreadIdRoute
  '/agents_/instructions': typeof AgentsInstructionsRoute
  '/review_/styles': typeof ReviewStylesRoute
  '/agents/': typeof AgentsIndexRoute
  '/agents/automations/$scheduleId': typeof AgentsAutomationsScheduleIdRoute
  '/agents/automations/new': typeof AgentsAutomationsNewRoute
  '/review_/repositories/$owner': typeof ReviewRepositoriesOwnerRoute
  '/agents/automations/': typeof AgentsAutomationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agents'
    | '/cloud-agents'
    | '/integrations'
    | '/login'
    | '/my-settings'
    | '/review'
    | '/usage'
    | '/agents/$threadId'
    | '/agents/instructions'
    | '/review/styles'
    | '/agents/'
    | '/agents/automations/$scheduleId'
    | '/agents/automations/new'
    | '/review/repositories/$owner'
    | '/agents/automations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/cloud-agents'
    | '/integrations'
    | '/login'
    | '/my-settings'
    | '/review'
    | '/usage'
    | '/agents/$threadId'
    | '/agents/instructions'
    | '/review/styles'
    | '/agents'
    | '/agents/automations/$scheduleId'
    | '/agents/automations/new'
    | '/review/repositories/$owner'
    | '/agents/automations'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agents'
    | '/cloud-agents'
    | '/integrations'
    | '/login'
    | '/my-settings'
    | '/review'
    | '/usage'
    | '/agents/$threadId'
    | '/agents_/instructions'
    | '/review_/styles'
    | '/agents/'
    | '/agents/automations/$scheduleId'
    | '/agents/automations/new'
    | '/review_/repositories/$owner'
    | '/agents/automations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AgentsRoute: typeof AgentsRouteWithChildren
  CloudAgentsRoute: typeof CloudAgentsRoute
  IntegrationsRoute: typeof IntegrationsRoute
  LoginRoute: typeof LoginRoute
  MySettingsRoute: typeof MySettingsRoute
  ReviewRoute: typeof ReviewRoute
  UsageRoute: typeof UsageRoute
  AgentsInstructionsRoute: typeof AgentsInstructionsRoute
  ReviewStylesRoute: typeof ReviewStylesRoute
  ReviewRepositoriesOwnerRoute: typeof ReviewRepositoriesOwnerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-settings': {
      id: '/my-settings'
      path: '/my-settings'
      fullPath: '/my-settings'
      preLoaderRoute: typeof MySettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cloud-agents': {
      id: '/cloud-agents'
      path: '/cloud-agents'
      fullPath: '/cloud-agents'
      preLoaderRoute: typeof CloudAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/review_/styles': {
      id: '/review_/styles'
      path: '/review/styles'
      fullPath: '/review/styles'
      preLoaderRoute: typeof ReviewStylesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents_/instructions': {
      id: '/agents_/instructions'
      path: '/agents/instructions'
      fullPath: '/agents/instructions'
      preLoaderRoute: typeof AgentsInstructionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$threadId': {
      id: '/agents/$threadId'
      path: '/$threadId'
      fullPath: '/agents/$threadId'
      preLoaderRoute: typeof AgentsThreadIdRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/agents/automations/': {
      id: '/agents/automations/'
      path: '/automations'
      fullPath: '/agents/automations/'
      preLoaderRoute: typeof AgentsAutomationsIndexRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/review_/repositories/$owner': {
      id: '/review_/repositories/$owner'
      path: '/review/repositories/$owner'
      fullPath: '/review/repositories/$owner'
      preLoaderRoute: typeof ReviewRepositoriesOwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/automations/new': {
      id: '/agents/automations/new'
      path: '/automations/new'
      fullPath: '/agents/automations/new'
      preLoaderRoute: typeof AgentsAutomationsNewRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/agents/automations/$scheduleId': {
      id: '/agents/automations/$scheduleId'
      path: '/automations/$scheduleId'
      fullPath: '/agents/automations/$scheduleId'
      preLoaderRoute: typeof AgentsAutomationsScheduleIdRouteImport
      parentRoute: typeof AgentsRoute
    }
  }
}

interface AgentsRouteChildren {
  AgentsThreadIdRoute: typeof AgentsThreadIdRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
  AgentsAutomationsScheduleIdRoute: typeof AgentsAutomationsScheduleIdRoute
  AgentsAutomationsNewRoute: typeof AgentsAutomationsNewRoute
  AgentsAutomationsIndexRoute: typeof AgentsAutomationsIndexRoute
}

const AgentsRouteChildren: AgentsRouteChildren = {
  AgentsThreadIdRoute: AgentsThreadIdRoute,
  AgentsIndexRoute: AgentsIndexRoute,
  AgentsAutomationsScheduleIdRoute: AgentsAutomationsScheduleIdRoute,
  AgentsAutomationsNewRoute: AgentsAutomationsNewRoute,
  AgentsAutomationsIndexRoute: AgentsAutomationsIndexRoute,
}

const AgentsRouteWithChildren =
  AgentsRoute._addFileChildren(AgentsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AgentsRoute: AgentsRouteWithChildren,
  CloudAgentsRoute: CloudAgentsRoute,
  IntegrationsRoute: IntegrationsRoute,
  LoginRoute: LoginRoute,
  MySettingsRoute: MySettingsRoute,
  ReviewRoute: ReviewRoute,
  UsageRoute: UsageRoute,
  AgentsInstructionsRoute: AgentsInstructionsRoute,
  ReviewStylesRoute: ReviewStylesRoute,
  ReviewRepositoriesOwnerRoute: ReviewRepositoriesOwnerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
